--[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------
This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.

Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
      Once you've done that, copy and paste the job to this file and edit it.

The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua

For examples and explanation please visit this wiki page:
https://darkrp.miraheze.org/wiki/DarkRP:CustomJobFields

Add your custom jobs under the following line:
---------------------------------------------------------------------------]]

-- Autorem tych prac jest: Max White#8603 oraz Inferno Black#8735
-- © Prawa autorskie zastrzeżone.
-- Zakazuje usuwania linijki o autorze oraz uzycia do celów komercyjnych.

local GAMEMODE = GAMEMODE or GM

--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
---TEAM_CITIZEN = DarkRP.createJob("Citizen", {
  --  color = Color(255, 120, 0, 255),
  --  model = {
   --     "models/classd/player/prisoners/jumpsuitm01.mdl",
---"models/classd/player/prisoners/jumpsuitm02.mdl",
 --       "models/classd/player/prisoners/jumpsuitm03.mdl",
 --       "models/classd/player/prisoners/jumpsuitm04.mdl",
 --       "models/classd/player/prisoners/jumpsuitm05.mdl",
 --       "models/classd/player/prisoners/jumpsuitm06.mdl",
--		"models/classd/player/prisoners/jumpsuitm07.mdl",
 --   },
 ---   description = [[Klasa D jest to domyślna klasa która jest brana na Badania]],
--    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
--    command = "citizen",
--    max = 0,
 --   salary = GAMEMODE.Config.normalsalary,
 --   admin = 0,
 --   vote = false,
--    hasLicense = false,
 --   candemote = false,
  --  category = "Citizens",
--	customCheck = function(ply) return
 --       table.HasValue({"STEAM_0:0:96053498"}, ply:SteamID())
 --   end,
--})

TEAM_KADET = DarkRP.createJob("Kadet", {
    color = Color(194, 191, 99, 255),
    model = {
        "models/cadet_blue/pm_training_cadet_alpha.mdl",
        "models/cadet_red/pm_training_cadet_bravo.mdl",
        "models/cadet_green/pm_training_cadet_domino.mdl",
        "models/cadet_orange/pm_training_cadet_zeta.mdl",
    },
    description = [[Nowe osoby]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "kadet",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Kadet",
})
--327TH--
TEAM_KOMANDOR = DarkRP.createJob("Dowódca 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/bly.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "komandor",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_OFICERWYK = DarkRP.createJob("Oficer Wykonawczy 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/cta/tc13j/cc.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "oficerwyk",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_OPIEKUNMED = DarkRP.createJob("Opiekun Medyków 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/Officer_medic.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "opmed",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_INZYNIER = DarkRP.createJob("Inżynier Główny 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/officer_engineer.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "inzynier",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_OPPIL = DarkRP.createJob("Opiekun Pilotów 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/officer_pilot.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "opiekunpil",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_MEDIC327 = DarkRP.createJob("Medyk 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/medic.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "medic327",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_PILOT327 = DarkRP.createJob("Pilot 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/pilot.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "pilot327",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_PIECH = DarkRP.createJob("Piechur 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/trooper.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "piechur327",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_INZCH = DarkRP.createJob("Inżynier 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "inz327",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_ARC327 = DarkRP.createJob("ARC 327th", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[327. Korpus Gwiezdny jest korpusem wojskowym Wielkiej Armii Republiki, złożonym z żołnierzy-klonów wyhodowanych do walki dla Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "arc327",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})

TEAM_AAYLA327 = DarkRP.createJob("Aayla Secura", {
    color = Color(207, 200, 4, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_aayala.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "alysa327",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "327th",
})
--1--
TEAM_MEDST = DarkRP.createJob("Medyk 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/paratrooper_medic.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "med1st",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_HEAVYST = DarkRP.createJob("Heavy 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/heavy.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "hevi1st",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_PILST = DarkRP.createJob("Pilot 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/pilot.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "pilst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_RECO1ST = DarkRP.createJob("Rekrut odziałowy 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/trooper.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "reclst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_OFP1ST = DarkRP.createJob("Oficer pilot 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/officer_pilot.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "OFPlst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_OFW1ST = DarkRP.createJob("Oficer wykonawczy 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/327/tc13j/officer_instructor.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "OFWlst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_OFHH1ST = DarkRP.createJob("Oficer heavy 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/officer_heavy.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "OFHHlst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_OFMM1ST = DarkRP.createJob("Oficer medyk 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/Officer_paratrooper_medic.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "OFMMlst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_DOW1ST = DarkRP.createJob("Dowódca 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/atin.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "DOWlst",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})

TEAM_ARC1ST = DarkRP.createJob("ARC 1ST", {
    color = Color(2, 64, 247, 255),
    model = {
        "models/jajoff/sps/myt/tc13j/arc_barc.mdl",
    },
    description = [[Pierwszy Legion jest elitarnym legionem szturmowców w siłach zbrojnych Imperium Galaktycznego.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "arc1st",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "1ST",
})
--501th--
TEAM_MED501 = DarkRP.createJob("Medyk 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/medic.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej. ]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "med501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_PIL501 = DarkRP.createJob("Pilot 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/pilot.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "pil501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_HEV501 = DarkRP.createJob("Heavy 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/heavy.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "hev501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_RECO501 = DarkRP.createJob("Rekrut oddziałowy 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/trooper.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "reco501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_OFC501 = DarkRP.createJob("Oficer 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/officer_instructor.mdl",
        "models/jajoff/sps/327/tc13j/jedi.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ofc501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_OFW501 = DarkRP.createJob("Oficer wykonawczy 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/custom/tc13j/axelszambiarz.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ofw501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_DOW501 = DarkRP.createJob("Rex", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/player/test/rex.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "dow501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_OFH501 = DarkRP.createJob("Oficer heavy 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/officer_heavy.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ofh501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_OFP501 = DarkRP.createJob("Oficer pilot 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/officer_pilot.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "asd501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_OFM501 = DarkRP.createJob("Oficer medyk 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/501/tc13j/Officer_medic.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "oftjas501",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_ARC501 = DarkRP.createJob("ARC 501th", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[Batalion Klonów legion poprzedzał Imperium Galaktyczne byli znani ze swojej odwagi, niekonwencjonalnej taktyki i lojalności wobec Republiki Galaktycznej.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "arc501th",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_AHSOKA501 = DarkRP.createJob("Ahsoka Tano", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_ahsoka_v1.mdl",
		"models/tfa/comm/gg/pm_sw_ahsoka_v2.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "asoka501th",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})

TEAM_ANAKIN501 = DarkRP.createJob("Anakin Skywalker", {
    color = Color(163, 0, 14, 255),
    model = {
        "models/tfa/comm/pm_sw_anakin_skywalker.mdl",
		"models/tfa/comm/gg/pm_sw_anakin_v2.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "anakinw501th",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "501th",
})
--CG--
TEAM_HCG = DarkRP.createJob("Hound CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/hound.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "hceqcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_RCG = DarkRP.createJob("Riot CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/officer_engineer.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "rxcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_SCG = DarkRP.createJob("Shock CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/shock.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "sqqcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_RAACG = DarkRP.createJob("Rekrut CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/trooper.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "rrcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})
 
TEAM_OFCG = DarkRP.createJob("Oficer CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/krristof/91st/Officer/Officer.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ofasadcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_OFWCG = DarkRP.createJob("Oficer wykonawczy CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/krristof/91st/EXO/EXO.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "qwecg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_DOWCG = DarkRP.createJob("Dowódca CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/thor.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "downcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_OFPPCG = DarkRP.createJob("Oficer pilot CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/officer_pilot.mdl",  
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ppppcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_PPCG = DarkRP.createJob("Pilot CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/pilot.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "oiucg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_MEDOFCG = DarkRP.createJob("Oficer medyk CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/Officer_paratrooper_medic.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "mdeopcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_MEDCG = DarkRP.createJob("Medyk CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/tracker_medic.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "gukcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_MASCG = DarkRP.createJob("Massif CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/mrpounder1/player/massif.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"sk_massif_swep"},
    command = "ardcg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})

TEAM_ARCCG = DarkRP.createJob("ARC CG", {
    color = Color(0, 163, 125, 255),
    model = {
        "models/jajoff/sps/CGA/tc13j/arc_barc.mdl",
    },
    description = [[Coruscant Guard była oddziałem elitarnych żołnierzy uderzeniowych klonów Wielkiej Armii Republiki]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "arccg",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CG",
})
--41ST--
TEAM_DOW41 = DarkRP.createJob("Dowódca 41ST", {
    color = Color(214, 203, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[41. Korpus Elitarny, znany po prostu jako Elite Corps, jest korpusem wojskowym Wielkiej Armii Republiki.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ddd41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_OOO41 = DarkRP.createJob("Oficer wykonawczy 41ST", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[41. Korpus Elitarny, znany po prostu jako Elite Corps, jest korpusem wojskowym Wielkiej Armii Republiki.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "uuu41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_SNIPER41 = DarkRP.createJob("Snajper 41ST", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[41. Korpus Elitarny, znany po prostu jako Elite Corps, jest korpusem wojskowym Wielkiej Armii Republiki.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "snip41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_ZW41 = DarkRP.createJob("Zwiadowca 41ST", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[41. Korpus Elitarny, znany po prostu jako Elite Corps, jest korpusem wojskowym Wielkiej Armii Republiki.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "zwid41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_PL41 = DarkRP.createJob("Pilot 41ST", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[41. Korpus Elitarny, znany po prostu jako Elite Corps, jest korpusem wojskowym Wielkiej Armii Republiki.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "pil41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_ARC41 = DarkRP.createJob("ARC 41ST", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[41. Korpus Elitarny, znany po prostu jako Elite Corps, jest korpusem wojskowym Wielkiej Armii Republiki.]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "ark41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_LUM41 = DarkRP.createJob("Luminara Unduli", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_luminara.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "unduli41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_BAR41 = DarkRP.createJob("Barriss Offee", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_barriss.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "offee41",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "41st",
})

TEAM_MAC91 = DarkRP.createJob("Mace Windu", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/player/mace/mace.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wind91",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "91st",
})

TEAM_ADI91 = DarkRP.createJob("Adi Gallia", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_adigallia.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "gallia91",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "91st",
})

TEAM_STASS91 = DarkRP.createJob("Stass Allie 91", {
    color = Color(101, 140, 0, 255),
    model = {
        "models/jajoff/sps/327/tc13j/engineer.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "allie91",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "91st",
})
--RC--
TEAM_TRERC = DarkRP.createJob("Trener RC", {
    color = Color(133, 73, 0, 255),
    model = {
        "models/jajoff/sps/arc/tc13j/regse.mdl",
    },
    description = [[Szkoleniowiec jednostek]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "nrerc",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "RC",
})

TEAM_DOWTRERC = DarkRP.createJob("Dowódca RC", {
    color = Color(133, 73, 0, 255),
    model = {
        "models/jajoff/sps/arc/tc13j/visio.mdl",
    },
    description = [[Dowódca szkoleń jednostek]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "dowenrerc",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "RC",
})
--DOWÓDZTWO--
TEAM_DOW = DarkRP.createJob("Dowództwo", {
    color = Color(105, 105, 105, 255),
    model = {
        "models/jajoff/sps/custom/tc13j/tobisimp.mdl",
        "models/jajoff/sps/custom/tc13j/major_niesmiesznow.mdl",
		"models/jajoff/sps/custom/tc13j/trol.mdl",
    },
    description = [[Zarządza wszystkim]],
    weapons = {"defuse_kit", "pe_target_marker", "stunstick", "cross_arms_swep", "cross_arms_infront_swep", "salute_swep", "weapon_cuff_elastic", "weapon_bactainjector", "weapon_bactanade", "jet_mk1", "rw_sw_stun_e11", "rw_sw_dual_dc17s", "alydus_fortificationbuildertablet", "alydus_fusioncutter"},
    command = "Dowmnv",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "DOWÓDZTWO",
})
--Jedi--
TEAM_YODA = DarkRP.createJob("Yoda", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_yoda.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "yo",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_KENOBI = DarkRP.createJob("Obi-Wan Kenobi", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_obiwan_alt.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "kebabi",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_STAS = DarkRP.createJob("Stass Allie", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/jajoff/sps/327/tc13j/arc.mdl",
        "models/jajoff/sps/327/tc13j/jedi.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "allicee",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_KIT = DarkRP.createJob("Kit Fisto", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/player/valley/LGN/kitfisto_diver/kitfisto_diver.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "fisto",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_COLE = DarkRP.createJob("Coleman Kcaj", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/jajoff/sps/327/tc13j/arc.mdl",
        "models/jajoff/sps/327/tc13j/jedi.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "mank",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_ADIMUD = DarkRP.createJob("Ki-Adi-Mundi", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/tfa/comm/gg/pm_sw_mundi.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "kidi",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_TIIN = DarkRP.createJob("Saesee Tiin", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/cultist_kun/sw/saesee_tiin.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "sasee",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})

TEAM_PLO = DarkRP.createJob("Plo Koon", {
    color = Color(0, 145, 143, 255),
    model = {
        "models/player/plokoon/plokoon.mdl",
    },
    description = [[Jedi]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "koon",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Jedi",
})
--187--
TEAM_MAC187 = DarkRP.createJob("Mace Windu 187th", {
    color = Color(214, 203, 0, 255),
    model = {
        "models/player/mace/mace.mdl",
    },
    description = [[Dowódca jednostki 187th]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wsind187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_DZIAL187 = DarkRP.createJob("Działonowy 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_trooper/gingers_187th_trooper_2.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wdziale187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_KIER187 = DarkRP.createJob("Kierowca 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_aerial_recon/gingers_187th_aerial_recon.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wdkra187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_TROPR187 = DarkRP.createJob("Troper 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_trooper/gingers_187th_trooper.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wdtrpa187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_DOWEU187 = DarkRP.createJob("Dowódca 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_com_airborne/gingers_187th_com_airborne.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wdowus187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_DOF187 = DarkRP.createJob("Oficer 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_lieutenant/gingers_187th_lieutenant.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wdowf187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_INXY187 = DarkRP.createJob("Inżynier 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_engineer/gingers_187th_engineer.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wdinz187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_IJJT187 = DarkRP.createJob("JetTroper 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_jet/gingers_187th_jet.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wjjtr187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})

TEAM_IMD187 = DarkRP.createJob("Medyk 187th", {
    color = Color(98, 0, 128, 255),
    model = {
        "models/player/gingers_187th_medic/gingers_187th_medic.mdl",
    },
    description = [[187. Legion, znany również jako Batalion Ataku Mace'a Windu, był legionem elitarnych żołnierzy-klonów]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wmd187",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "187th",
})
--CT--
TEAM_ICT = DarkRP.createJob("CT", {
    color = Color(161, 46, 0, 255),
    model = {
        "models/jajoff/sps/cta/tc13j/trooper.mdl",
    },
    description = [[Klon]],
    weapons = {"weapon_physcannon", "weapon_hands", "weapon_fists", "keys", "surrender_animation_swep"},
    command = "wmctt",
    max = 1,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "CT",
})

---TEAM_POLICE = DarkRP.createJob("Civil Protection", {
  --  color = Color(25, 25, 170, 255),
  --  model = {"models/player/police.mdl", "models/player/police_fem.mdl"},
---description = [[.]],
  ---  weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
  --  command = "cp",
  --  max = 4,
  --  salary = GAMEMODE.Config.normalsalary * 1.45,
  ---  admin = 0,
 --   vote = true,
  --  hasLicense = true,
 --   ammo = {
----["pistol"] = 60,
    ---},
  --  category = "Civil Protection",
--	customCheck = function(ply) return
 --       table.HasValue({"STEAM_0:0:96053498"}, ply:SteamID())
   -- end,
---})

--TEAM_GANG = DarkRP.createJob("Gangster", {
--    color = Color(75, 75, 75, 255),
--    model = {
--        "models/player/Group03/Female_01.mdl",
--	},
--    description = [[]],
--    weapons = {},
--    command = "gangster",
--    max = 3,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    category = "Gangsters",
--})

---TEAM_MOB = DarkRP.createJob("Mob boss", {
 --   color = Color(25, 25, 25, 255),
 --   model = "models/player/gman_high.mdl",
 --   description = [[The Mob boss is the boss of the criminals in the city.
 --       With his power he coordinates the gangsters and forms an efficient crime organization.
  ---      He has the ability to break into houses by using a lockpick.
  --      The Mob boss posesses the ability to unarrest you.]],
  ---  weapons = {"lockpick", "unarrest_stick"},
 --   command = "mobboss",
 --   max = 1,
 --   salary = GAMEMODE.Config.normalsalary * 1.34,
 --   admin = 0,
  --  vote = false,
  --  hasLicense = false,
  --  category = "Gangsters",
	--customCheck = function(ply) return
  --      table.HasValue({}, ply:SteamID())
  --  end,
--})

--TEAM_GUN = DarkRP.createJob("Gun Dealer", {
--    color = Color(255, 140, 0, 255),
--    model = "models/player/monk.mdl",
--    description = [[A Gun Dealer is the only person who can sell guns to other people.
--        Make sure you aren't caught selling illegal firearms to the public! You might get arrested!]],
--    weapons = {},
--    command = "gundealer",
--    max = 2,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    category = "Citizens",
--})

--TEAM_MEDIC = DarkRP.createJob("Medic", {
--    color = Color(47, 79, 79, 255),
--    model = "models/player/kleiner.mdl",
--    description = [[With your medical knowledge you work to restore players to full health.
--        Without a medic, people cannot be healed.
--        Left click with the Medical Kit to heal other players.
--        Right click with the Medical Kit to heal yourself.]],
--    weapons = {"med_kit"},
--    command = "medic",
--    max = 3,
--    salary = GAMEMODE.Config.normalsalary,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    medic = true,
--    category = "Citizens",
--})

--TEAM_CHIEF = DarkRP.createJob("Civil Protection Chief", {
--    color = Color(20, 20, 255, 255),
--    model = "models/player/combine_soldier_prisonguard.mdl",
--    description = [[The Chief is the leader of the Civil Protection unit.
--        Coordinate the police force to enforce law in the city.
--        Hit a player with arrest baton to put them in jail.
--        Bash a player with a stunstick and they may learn to obey the law.
--        The Battering Ram can break down the door of a criminal, with a warrant for his/her arrest.
--        Type /wanted <name> to alert the public to the presence of a criminal.
--        Type /jailpos to set the Jail Position]],
--    weapons = {"arrest_stick", "unarrest_stick", "weapon_deagle2", "stunstick", "door_ram", "weaponchecker"},
--    command = "chief",
--    max = 1,
--    salary = GAMEMODE.Config.normalsalary * 1.67,
--    admin = 0,
--    vote = false,
--    hasLicense = true,
--    chief = true,
--    NeedToChangeFrom = TEAM_POLICE,
--    ammo = {
--        ["pistol"] = 60,
--    },
--    category = "Civil Protection",
--})

--TEAM_MAYOR = DarkRP.createJob("Mayor", {
--    color = Color(150, 20, 20, 255),
--    model = "models/player/breen.mdl",
--    description = [[The Mayor of the city creates laws to govern the city.
--    If you are the mayor you may create and accept warrants.
--    Type /wanted <name>  to warrant a player.
--    Type /jailpos to set the Jail Position.
--    Type /lockdown initiate a lockdown of the city.
--    Everyone must be inside during a lockdown.
--    The cops patrol the area.
--    /unlockdown to end a lockdown]],
--    weapons = {},
--    command = "mayor",
--    max = 1,
--    salary = GAMEMODE.Config.normalsalary * 1.89,
--    admin = 0,
--    vote = true,
--    hasLicense = false,
--    mayor = true,
--    category = "Civil Protection",
--})

--TEAM_HOBO = DarkRP.createJob("Hobo", {
--    color = Color(80, 45, 0, 255),
--    model = "models/player/corpse1.mdl",
--    description = [[The lowest member of society. Everybody laughs at you.
--        You have no home.
--        Beg for your food and money
--        Sing for everyone who passes to get money
--        Make your own wooden home somewhere in a corner or outside someone else's door]],
--    weapons = {"weapon_bugbait"},
--    command = "hobo",
--    max = 5,
--    salary = 0,
--    admin = 0,
--    vote = false,
--    hasLicense = false,
--    candemote = false,
--    hobo = true,
--    category = "Citizens",
--}) 

TEAM_ADMIN = DarkRP.createJob("Admin", {
    color = Color(255, 0, 0, 250),
	model = {
        "models/gonzo/battlelordsskins/red/redbattlelord1.mdl",
		"models/gonzo/battlelordsskins/red/redbattlelord2.mdl",
		"models/gonzo/battlelordsskins/red/redbattlelord3.mdl",
    },
    description = [[Jest to Administracja serwer obecna do pomocy inaczej AdminOnDuty]],
    weapons = {"arrest_stick", "door_ram", "stunstick", "gmod_tool"},
    command = "Admini",
    max = 5,
    salary = 1000,
    admin = 1,
    vote = false,
    hasLicense = true,
    candemote = true,
	mayor = true,
    category = "Administracja serwera",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100000)
        ply:SetHealth(100000)
        ply:SetArmor(1000)
        ply:SetBodygroup(0, 1)
        ply:SetBodygroup(1, 2)
    end
})

TEAM_MOD = DarkRP.createJob("Mod", {
    color = Color(255, 0, 0, 250),
	model = {
        "models/gonzo/battlelordsskins/green/greenbattlelord1.mdl",
		"models/gonzo/battlelordsskins/green/greenbattlelord2.mdl",
		"models/gonzo/battlelordsskins/green/greenbattlelord3.mdl",
    },
    description = [[Jest to Moderator serwer obecna do pomocy inaczej ModOnDuty]],
    weapons = {"arrest_stick", "stunstick", "gmod_tool"},
    command = "Mody",
    max = 4,
    salary = 1000,
    admin = 1,
    vote = false,
    hasLicense = true,
    candemote = true,
    category = "Administracja serwera",
	PlayerSpawn = function(ply)
        ply:SetMaxHealth(100000)
        ply:SetHealth(100000)
        ply:SetArmor(1000)
    end
})

if not DarkRP.disabledDefaults["modules"]["hungermod"] then
    TEAM_COOK = DarkRP.createJob("Cook", {
        color = Color(238, 99, 99, 255),
        model = "models/player/mossman.mdl",
        description = [[As a cook, it is your responsibility to feed the other members of your city.
            You can spawn a microwave and sell the food you make:
            /buymicrowave]],
        weapons = {},
        command = "cook",
        max = 2,
        salary = 45,
        admin = 0,
        vote = false,
        hasLicense = false,
        cook = true
    })
end

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
AddDoorGroup("Gundealer only", TEAM_GUN)


-- Agendas
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})

-- Group chats
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_KADET

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
	[TEAM_ADMIN] = true,
}

-- Hitman team
DarkRP.addHitmanTeam(TEAM_ADMIN)

-- Demote groups
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

-- Default categories
--DarkRP.createCategory{
 --   name = "Citizens",
 --   categorises = "jobs",
  --  startExpanded = true,
  --  color = Color(0, 107, 0, 255),
  --  canSee = fp{fn.Id, true},
  --  sortOrder = 255,
--}

----DarkRP.createCategory{
  --  name = "Civil Protection",
  --  categorises = "jobs",
  --  startExpanded = true,
 --   color = Color(25, 25, 170, 255),
  --  canSee = fp{fn.Id, true},
 --   sortOrder = 255,
---}

---DarkRP.createCategory{
  --  name = "Gangsters",
 --   categorises = "jobs",
 --   startExpanded = true,
 --   color = Color(75, 75, 75, 255),
 --   canSee = fp{fn.Id, true},
  --  sortOrder = 255,
----}

DarkRP.createCategory{
    name = "Administracja serwera",
    categorises = "jobs",
    startExpanded = true,
    color = Color(255, 13, 0),
    canSee = fp{fn.Id, true},
    sortOrder = 1,
}

DarkRP.createCategory{
    name = "Kadet",
    categorises = "jobs",
    startExpanded = true,
    color = Color(194, 191, 99),
    canSee = fp{fn.Id, true},
    sortOrder = 2,
}

DarkRP.createCategory{
    name = "RC",
    categorises = "jobs",
    startExpanded = true,
    color = Color(133, 73, 0),
    canSee = fp{fn.Id, true},
    sortOrder = 3,
}

DarkRP.createCategory{
    name = "327th",
    categorises = "jobs",
    startExpanded = true,
    color = Color(207, 200, 4),
    canSee = fp{fn.Id, true},
    sortOrder = 4,
}

DarkRP.createCategory{
    name = "1ST",
    categorises = "jobs",
    startExpanded = true,
    color = Color(2, 64, 247),
    canSee = fp{fn.Id, true},
    sortOrder = 5,
}

DarkRP.createCategory{
    name = "501th",
    categorises = "jobs",
    startExpanded = true,
    color = Color(163, 0, 14),
    canSee = fp{fn.Id, true},
    sortOrder = 6,
}

DarkRP.createCategory{
    name = "CG",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 163, 125),
    canSee = fp{fn.Id, true},
    sortOrder = 7,
}

DarkRP.createCategory{
    name = "41st",
    categorises = "jobs",
    startExpanded = false,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 8,
}

DarkRP.createCategory{
    name = "91st",
    categorises = "jobs",
    startExpanded = false,
    color = Color(101, 140, 0),
    canSee = fp{fn.Id, true},
    sortOrder = 9,
}

DarkRP.createCategory{
    name = "187th",
    categorises = "jobs",
    startExpanded = false,
    color = Color(98, 0, 128, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 10,
}

DarkRP.createCategory{
    name = "CT",
    categorises = "jobs",
    startExpanded = false,
    color = Color(161, 46, 0),
    canSee = fp{fn.Id, true},
    sortOrder = 11,
}

DarkRP.createCategory{
    name = "DOWÓDZTWO",
    categorises = "jobs",
    startExpanded = true,
    color = Color(105, 105, 105),
    canSee = fp{fn.Id, true},
    sortOrder = 12,
}

DarkRP.createCategory{
    name = "Jedi",
    categorises = "jobs",
    startExpanded = false,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 13,
}

DarkRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = false,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}

DarkRP.createCategory{
    name = "Pilot",
    categorises = "entities",
    startExpanded = true,
    color = Color(212, 125, 4),
    canSee = fp{fn.Id, true},
    sortOrder = 1,
}
